### ISSUE TITLE
Error when launching mc. 1.16.5 Mod Menu and Cloth are both downloaded.

### ISSUE THREAD

**Issue by wfanime** [PlagueTR/ChatTimestamps#1]
Uncaught exception in thread "main"
java.lang.RuntimeException: Error creating Mixin config plagueschattimestamps.mixins.json for mod plagueschattimestamps
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:95)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:153)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config plagueschattimestamps.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:153)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:100)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:87)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:93)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_17 could not be set. Level is not supported by the active JRE or ASM version (Java 16.0, ASM 9.5 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1570)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:557)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:502)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:430)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1293)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:148)
	... 6 more
What should I do

**Comment by PlagueTR** [comment]
My bad! I configured and built the mod for Java 17 for all versions of Mineraft.
For a temporary solution, you can install Java 17 (or newer) and run the game using that instead of the version you are using at the time (It seems to me that you are using Java 16).
There are many places to find and download JRE, if you are having trouble finding one. The one I use is from [Adoptium](https://adoptium.net/).
Alternatively, I can rebuild the mod to use Java 8 and upload it here when I get to my computer. (Minecraft 1.16 is built for Java 8.)

**Comment by PlagueTR** [comment]
I rebuilt the 1.16.2-1.16.5 version targeting Java 8 this time.
I had to zip the file first to upload here, but here it is:
[plagues-chat-timestamps-1.0.1+1.16.2-1.16.5.zip](https://github.com/PlagueTR/ChatTimestamps/files/12403963/plagues-chat-timestamps-1.0.1%2B1.16.2-1.16.5.zip)

**Comment by PlagueTR** [comment]
Closing for inactivity.
